<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 4               */
/* CACHE FILE: Generated: Tue, 05 Jan 2016 20:04:02 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_topictemplate_4 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['topicTemplatePostScreen'] = array('hasOneTemplate');


}

/* -- fieldTemplate --*/
function fieldTemplate($field) {
$IPBHTML = "";
$IPBHTML .= "" . (($field['instructions']) ? ("
  <div class='ipsPad'>
    <div class='message'>{{$field['field_id']}_instr}</div>
  </div>
") : ("")) . "
      <label for='template_field_{$field['field_id']}' class='ipsField_title' data-tooltip='test'>{{$field['field_id']}_label}" . (($field['required']==1) ? ("<span class='ipsForm_required'> * </span>") : ("")) . "</label>
      <div id='ttf_{$field['field_id']}' class='ipsField_content'>    
        {{$field['field_id']}_field}" . (($field['description']) ? ("
        <br/>
        <span class='desc lighter'>{{$field['field_id']}_desc}</span>
        ") : ("")) . "
      </div>";
return $IPBHTML;
}

/* -- formatCheckbox --*/
function formatCheckbox($field) {
$IPBHTML = "";
$IPBHTML .= "<input type='checkbox' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' value='1' class='__ttf' " . (($field['value']==1) ? ("checked='checked'") : ("")) . "/>";
return $IPBHTML;
}

/* -- formatDropdown --*/
function formatDropdown($field, $options) {
$IPBHTML = "";
$IPBHTML .= "<select name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' class='__ttf'>
  <option value=''>--</option>
  ".$this->__f__7c735b4665024ae2f3f44ae9ebde0230($field,$options)."</select>";
return $IPBHTML;
}


function __f__7c735b4665024ae2f3f44ae9ebde0230($field, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $opt )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <option value='{$opt['value']}' " . (($opt['value']==$field['value']) ? ("SELECTED") : ("")) . ">{$opt['label']}</option>
  
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- formatMulti --*/
function formatMulti($field, $options) {
$IPBHTML = "";
$IPBHTML .= "<select name='template_field_{$field['field_id']}[]' id='template_field_{$field['field_id']}[]' multiple size='5' class='__ttf'>
  <option value=''>--</option>
  ".$this->__f__6919897903b61d39ad1fbd08b16c89d0($field,$options)."</select>";
return $IPBHTML;
}


function __f__6919897903b61d39ad1fbd08b16c89d0($field, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $opt )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <option value='{$opt['value']}' " . ((in_array($opt['value'],explode(",",$field['value']))) ? ("SELECTED") : ("")) . ">{$opt['label']}</option>
  
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- formatMultiCheckbox --*/
function formatMultiCheckbox($field, $options) {
$IPBHTML = "";
$IPBHTML .= "".$this->__f__4cfd2b50a678e20a1e18b6ea18b9a132($field,$options)."";
return $IPBHTML;
}


function __f__4cfd2b50a678e20a1e18b6ea18b9a132($field, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $opt )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
  <input type='checkbox' name='template_field_{$field['field_id']}[]' id='template_field_{$field['field_id']}[]' value='{$opt['value']}' class='__ttf' " . ((in_array($opt['value'],explode(",",$field['value']))) ? ("CHECKED") : ("")) . ">&nbsp;{$opt['label']}</input><br/>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- formatRadio --*/
function formatRadio($field, $options) {
$IPBHTML = "";
$IPBHTML .= "".$this->__f__9752fbe6e2121b84f5d9c4d6cf86b420($field,$options)."";
return $IPBHTML;
}


function __f__9752fbe6e2121b84f5d9c4d6cf86b420($field, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $opt )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
  <input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' value='{$opt['value']}' class='__ttf' " . (($opt['value']==$field['value']) ? ("CHECKED") : ("")) . ">{$opt['label']}</input>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- formatRatingField --*/
function formatRatingField($field) {
$IPBHTML = "";
$IPBHTML .= "<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_1' class='__ttf' value='1' " . (($field['value']==1) ? ("CHECKED") : ("")) . "> 1</input>&nbsp;&nbsp;
<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_2' class='__ttf' value='2' " . (($field['value']==2) ? ("CHECKED") : ("")) . "> 2</input>&nbsp;&nbsp;
<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_3' class='__ttf' value='3' " . (($field['value']==3) ? ("CHECKED") : ("")) . "> 3</input>&nbsp;&nbsp;
<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_4' class='__ttf' value='4' " . (($field['value']==4) ? ("CHECKED") : ("")) . "> 4</input>&nbsp;&nbsp;
<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_5' class='__ttf' value='5' " . (($field['value']==5) ? ("CHECKED") : ("")) . "> 5</input>";
return $IPBHTML;
}

/* -- formatTextArea --*/
function formatTextArea($field) {
$IPBHTML = "";
$IPBHTML .= "<textarea name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' class='__ttf'>{$field['value']}</textarea>";
return $IPBHTML;
}

/* -- formatTextField --*/
function formatTextField($field) {
$IPBHTML = "";
$IPBHTML .= "<input type='text' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' value='{$field['value']}' class='__ttf'/>";
return $IPBHTML;
}

/* -- topicTemplatePostScreen --*/
function topicTemplatePostScreen($forumId, $topicId=0, $template, $currentSet, $sets) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_topictemplate', $this->_funcHooks['topicTemplatePostScreen'] ) )
{
$count_4d5fdc82f708b89ded1620588dd0af0f = is_array($this->functionData['topicTemplatePostScreen']) ? count($this->functionData['topicTemplatePostScreen']) : 0;
$this->functionData['topicTemplatePostScreen'][$count_4d5fdc82f708b89ded1620588dd0af0f]['forumId'] = $forumId;
$this->functionData['topicTemplatePostScreen'][$count_4d5fdc82f708b89ded1620588dd0af0f]['topicId'] = $topicId;
$this->functionData['topicTemplatePostScreen'][$count_4d5fdc82f708b89ded1620588dd0af0f]['template'] = $template;
$this->functionData['topicTemplatePostScreen'][$count_4d5fdc82f708b89ded1620588dd0af0f]['currentSet'] = $currentSet;
$this->functionData['topicTemplatePostScreen'][$count_4d5fdc82f708b89ded1620588dd0af0f]['sets'] = $sets;
}
$IPBHTML .= "<script type='text/javascript'>
ipb.topicTemplate.forumId = {$forumId};
ipb.topicTemplate.topicId = {$topicId};
</script>
" . (($sets['required'] && count($sets['sets'])==1) ? ("<br /><br />
  <input type='hidden' name='set_id' id='set_id' value='{$currentSet['set_id']}' />
  <div id='set_description' class='ipsPad " . (($currentSet['description']) ? ("message") : ("")) . "'>{$currentSet['description']}</div>
  <br />") : ("<li class='ipsField ipsField_select'>
    <label for='set_id' class='ipsField_title'>Select Template</label>
    <div class='ipsField_content'>
      <select name='set_id' id='set_id'>
        " . ((!$sets['required']) ? ("<option value='0'>No Template</option>") : ("")) . "".$this->__f__e81f57beb566b0ac5bdd753397659523($forumId,$topicId,$template,$currentSet,$sets)."      </select>
      <br />
      <br />
      <div id='set_description' class='ipsPad " . (($currentSet['description']) ? ("message") : ("")) . "'>{$currentSet['description']}</div>
    </div>
  </li>")) . "
<div id='set_fields'>
{$template}
</div>";
return $IPBHTML;
}


function __f__e81f57beb566b0ac5bdd753397659523($forumId, $topicId=0, $template, $currentSet, $sets)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sets['sets'] as $set )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
          <option value='{$set['set_id']}' " . (($set['set_id']==$currentSet['set_id']) ? ("SELECTED") : ("")) . ">{$set['name']}</option>
        
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicTemplatePostTemplate --*/
function topicTemplatePostTemplate($fields) {
$IPBHTML = "";
$IPBHTML .= "" . ((is_array($fields) && count($fields)) ? ("".$this->__f__7c562fd2e3eba9413fc6c37df0f0a0b7($fields)."") : ("")) . "";
return $IPBHTML;
}


function __f__7c562fd2e3eba9413fc6c37df0f0a0b7($fields)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $fields as $field )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <li class='ipsField'>
      {$field}
    </li>
  
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>