<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 0               */
/* CACHE FILE: Generated: Tue, 19 Jan 2016 05:37:47 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_donate_external_0 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['donateGraph'] = array('fixedGraphColor');
$this->_funcHooks['donationAmount'] = array('showFee','calculateFee','anonymous_amount');
$this->_funcHooks['donorName'] = array('donorName','donor','anonymous');
$this->_funcHooks['featuredGoalsSidebar'] = array('hasDescription','privateGoal','amount_dropdown','showDonateBox','makeDonationPerms','goal_row','hasgoals');
$this->_funcHooks['latestDonationsPortal'] = array('donation_row','hasdonations');
$this->_funcHooks['latestDonationsSidebar'] = array('donation_row','hasdonations');
$this->_funcHooks['profileList'] = array('has_note');
$this->_funcHooks['topDonorsSidebar'] = array('donation_row','hasdonations');
$this->_funcHooks['topicLink'] = array('showDonorLink');
$this->_funcHooks['totalStats'] = array('calculateFee','showTotalFees','donationsFull','showGoalStats','amount_dropdown','showDonateBox','makeDonationPerms');


}

/* -- donateGraph --*/
function donateGraph($percent='', $g_id, $width='90%', $height='12px') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['donateGraph'] ) )
{
$count_56e0ef53da7beb725f9937ffa0a10973 = is_array($this->functionData['donateGraph']) ? count($this->functionData['donateGraph']) : 0;
$this->functionData['donateGraph'][$count_56e0ef53da7beb725f9937ffa0a10973]['percent'] = $percent;
$this->functionData['donateGraph'][$count_56e0ef53da7beb725f9937ffa0a10973]['g_id'] = $g_id;
$this->functionData['donateGraph'][$count_56e0ef53da7beb725f9937ffa0a10973]['width'] = $width;
$this->functionData['donateGraph'][$count_56e0ef53da7beb725f9937ffa0a10973]['height'] = $height;
}

if( $percent >= 0 AND $percent <= 24.99 )
{
    $statusImg = "status1.png";
}
else if( $percent >= 25 AND $percent <= 49.99 )
{
    $statusImg = "status2.png";
}
else if( $percent >= 50 AND $percent <= 74.99 )
{
    $statusImg = "status3.png";
}
else if( $percent >= 75 )
{
    $statusImg = "status4.png";
}
$IPBHTML .= "<style type='text/css'>
#progress-container_{$g_id} {
  border: 1px solid #ccc; 
  width: {$width}; 
  height: {$height};
  margin: 0; 
  padding: 1px;
  background: white;

}
#progress-container_{$g_id} > div {
" . (($this->settings['dt_bar_bg']) ? ("
     background-color: {$this->settings['dt_bar_bg']};
") : ("
     background-color: #5C87C7;
     background-image: url({$this->settings['img_url']}/{$statusImg});
     background-repeat: no-repeat;
")) . "
     height: 100%;
}
</style>

<div id='progress-container_{$g_id}' title='{$percent}% {$this->lang->words['of_goal_reached']}'><div style='width: {$percent}%'></div></div>";
return $IPBHTML;
}

/* -- donationAmount --*/
function donationAmount($donation) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['donationAmount'] ) )
{
$count_d5e0fe60f513075141eecefbc39ca977 = is_array($this->functionData['donationAmount']) ? count($this->functionData['donationAmount']) : 0;
$this->functionData['donationAmount'][$count_d5e0fe60f513075141eecefbc39ca977]['donation'] = $donation;
}
$IPBHTML .= "" . ((!$donation['anon_amount'] && !$donation['g_private']) ? ("<span " . (($this->settings['dt_include_fees']) ? ("data-tooltip=\"{$donation['c_symbol']} " . $this->registry->getClass('class_localization')->formatNumber( $donation['fees'], 2 ) . " {$this->lang->words['fee']}\"") : ("")) . ">{$donation['c_symbol']} " . (($this->settings['dt_include_fees']) ? ("" . $this->registry->getClass('class_localization')->formatNumber( $donation['amount']-$donation['fees'], 2 ) . "") : ("" . $this->registry->getClass('class_localization')->formatNumber( $donation['amount'], 2 ) . "")) . "</span>") : ("--")) . "";
return $IPBHTML;
}

/* -- donorName --*/
function donorName($r=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['donorName'] ) )
{
$count_92993870414cd59b7bbf401ae9ea518f = is_array($this->functionData['donorName']) ? count($this->functionData['donorName']) : 0;
$this->functionData['donorName'][$count_92993870414cd59b7bbf401ae9ea518f]['r'] = $r;
}
$IPBHTML .= "" . ((!$r['anon']) ? ("" . (($r['member_id'] AND $r['member_name']) ? ("
<a hovercard-ref=\"member\" hovercard-id=\"{$r['member_id']}\" class=\"_hovertrigger url fn\" href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", "public",'' ), "{$r['member_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$r['member_name']}</a>
") : ("" . (($r['member_name']) ? ("
{$r['member_name']}
") : ("
<i>{$this->lang->words['offline_donation']}</i>
")) . "")) . "") : ("

<i>{$this->lang->words['anonymous']}</i>

")) . "";
return $IPBHTML;
}

/* -- featuredGoalsSidebar --*/
function featuredGoalsSidebar($goals=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['featuredGoalsSidebar'] ) )
{
$count_13178ecd8efefb6b2313f4c4673414ca = is_array($this->functionData['featuredGoalsSidebar']) ? count($this->functionData['featuredGoalsSidebar']) : 0;
$this->functionData['featuredGoalsSidebar'][$count_13178ecd8efefb6b2313f4c4673414ca]['goals'] = $goals;
}
$IPBHTML .= "<div class='ipsSideBlock'>
	<h3>{$this->lang->words['featured_donation_goals']}</h3>
        <div class='_sbcollapsable'>
	<ul class='ipsList_inline'>
		" . ((is_array( $goals ) && count( $goals )) ? ("
			".$this->__f__a0adecb011fbc3574abb05051be1a34b($goals)."		") : ("")) . "
	</ul>
        </div>
</div>";
return $IPBHTML;
}


function __f__40360323c21e556406e6b900c36bb7e9($goals=array(),$r='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( explode(",", $this->settings['dt_amounts'] ) as $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <option value=\"{$value}\">{$value}</option>
    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__a0adecb011fbc3574abb05051be1a34b($goals=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $goals as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li class='clearfix'>
<div class='list_content ipsPad_half'>
<h2><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_goal&amp;id={$r['g_id']}", "public",'' ), "{$r['seo_name']}", "view_goal" ) . "'>{$r['g_name']}</a></h2>
" . (($r['g_desc']) ? ("<p>{$r['g_desc']}</p>") : ("")) . "

" . ((!$r['g_private']) ? ("<br />" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donateGraph' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donateGraph($r['status'], $r['g_id']) : '' ) . "
<span class='ipsType_smaller desc lighter'>{$r['status']}% {$this->lang->words['complete']} - {$r['c_symbol']}{$r['g_received']} {$this->lang->words['of_this']} {$r['c_symbol']}{$r['g_amount']} {$this->lang->words['goal_reached']}</span><br />") : ("")) . "

" . (($this->memberData['g_dt_donate']) ? ("" . (($this->settings['dt_disable_completed'] && ( $this->caches['donate_cache']['total_donations'] + $this->caches['donate_cache']['total_fees'] ) >= $this->caches['donate_cache']['total_goals']) ? (" 
     &nbsp;
") : ("<br /><form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=display&amp;do=donate&amp;goal={$r['g_id']}", "public",'' ), "", "" ) . "' method=\"post\">
 
    " . (($this->settings['dt_amounts']) ? ("
    <select name='amount'>
    ".$this->__f__40360323c21e556406e6b900c36bb7e9($goals,$r)."    </select>
    ") : ("
    <input type='text' id='enter_amount2' name='amount' class='input_text' size='4' />
    <script type='text/javascript'>
    $('enter_amount2').defaultize( \"5.00\" );
    </script>
    ")) . "
    
    <input type='submit' class='input_submit' value='{$this->lang->words['donate']}' />
    </form>")) . "") : ("")) . "
</div>
				</li>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- latestDonationsPortal --*/
function latestDonationsPortal($donations=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['latestDonationsPortal'] ) )
{
$count_447e92e835925e48f149d0e53f469536 = is_array($this->functionData['latestDonationsPortal']) ? count($this->functionData['latestDonationsPortal']) : 0;
$this->functionData['latestDonationsPortal'][$count_447e92e835925e48f149d0e53f469536]['donations'] = $donations;
}
$IPBHTML .= "<div class='ipsSideBlock'>
	<h3>{$this->lang->words['latest_donations']}</h3>
        <div class='_sbcollapsable'>
	<ul class='ipsList'>
		" . ((is_array( $donations ) && count( $donations )) ? ("
			".$this->__f__05070af1d3c1d1d0ef2ccf4d9b6c9ea3($donations)."		") : ("")) . "
	</ul>
        </div>
</div>";
return $IPBHTML;
}


function __f__05070af1d3c1d1d0ef2ccf4d9b6c9ea3($donations=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $donations as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li class='clearfix'>
<div class='list_content ipsPad_half'>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donorName' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donorName($r) : '' ) . " ( " . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donationAmount' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donationAmount($r) : '' ) . " )<br />

<span class='date'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['date'],"long", 0)) . "</span>
</div>
				</li>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- latestDonationsSidebar --*/
function latestDonationsSidebar($donations=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['latestDonationsSidebar'] ) )
{
$count_b524ffa581b507f4639107a116f9f10d = is_array($this->functionData['latestDonationsSidebar']) ? count($this->functionData['latestDonationsSidebar']) : 0;
$this->functionData['latestDonationsSidebar'][$count_b524ffa581b507f4639107a116f9f10d]['donations'] = $donations;
}
$IPBHTML .= "<div class='ipsSideBlock'>
	<h3>{$this->lang->words['latest_donations']}</h3>
        <div class='_sbcollapsable'>
	<ul class='ipsList_withminiphoto'>
		" . ((is_array( $donations ) && count( $donations )) ? ("
			".$this->__f__4cead1619c37343cb59cd8bb953ca839($donations)."		") : ("")) . "
	</ul>
        </div>
</div>";
return $IPBHTML;
}


function __f__4cead1619c37343cb59cd8bb953ca839($donations=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $donations as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li class='clearfix'>

<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['member_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}' class='ipsUserPhotoLink left'><img src='{$r['pp_mini_photo']}' alt=\"{$r['members_display_name']}{$this->lang->words['users_photo']}\" class='ipsUserPhoto ipsUserPhoto_mini' /></a>

<div class='list_content'>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donorName' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donorName($r) : '' ) . " ( " . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donationAmount' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donationAmount($r) : '' ) . " )<br />

<p class=\"desc ipsType_smaller\">" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['date'],"long", 0)) . "</p>
</div>
				</li>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- profileList --*/
function profileList($data=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['profileList'] ) )
{
$count_4a3c9c787d8fb91edc78233501ea45a3 = is_array($this->functionData['profileList']) ? count($this->functionData['profileList']) : 0;
$this->functionData['profileList'][$count_4a3c9c787d8fb91edc78233501ea45a3]['data'] = $data;
}

if ( ! isset( $this->registry->templateStriping['cat_row'] ) ) {
$this->registry->templateStriping['cat_row'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "<h3 class='maintitle'>{$this->lang->words['member_donations']}</h3>
<div class='ipsBox'>
<div class='ipsBox_container'>

<table class=\"ipb_table\">
<tr class='header hide'>
<th scope='col'>{$this->lang->words['donor_name']}</th>
<th scope='col'>{$this->lang->words['donation_note']}</th>
<th scope='col' class='short'>{$this->lang->words['donation_date']}</th>
<th scope='col' class='short'>{$this->lang->words['amount']}</th>
</tr>".$this->__f__1388c69e552801eefc5c3597dd5a89e2($data)."</table>

</div>
</div>";
return $IPBHTML;
}


function __f__1388c69e552801eefc5c3597dd5a89e2($data=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data as $a => $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "

<tr class='" .  IPSLib::next( $this->registry->templateStriping["cat_row"] ) . "'>
	<td class='altrow'>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donorName' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donorName($r) : '' ) . "</td>
<td class='altrow'>" . (($r['note']) ? ("{$r['note']}") : ("<i>{$this->lang->words['no_note']}</i>")) . "</td>
<td class='short'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['date'],"long", 0)) . "</td>
<td class='altrow short'><strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donationAmount' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donationAmount($r) : '' ) . "</strong></td>	
</tr>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topDonorsSidebar --*/
function topDonorsSidebar($topDonors=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['topDonorsSidebar'] ) )
{
$count_53732f92b320f7cb8c58c4c29d5ee23c = is_array($this->functionData['topDonorsSidebar']) ? count($this->functionData['topDonorsSidebar']) : 0;
$this->functionData['topDonorsSidebar'][$count_53732f92b320f7cb8c58c4c29d5ee23c]['topDonors'] = $topDonors;
}
$IPBHTML .= "<div class='ipsSideBlock'>
	<h3>{$this->lang->words['top_donors']}</h3>
        <div class='_sbcollapsable'>
	<ul class='ipsList_inline'>
		" . ((is_array( $topDonors ) && count( $topDonors )) ? ("
			".$this->__f__ce2673d57a1c50c03f47bfeeb4a98b41($topDonors)."		") : ("")) . "
	</ul>
        </div>
</div>";
return $IPBHTML;
}


function __f__ce2673d57a1c50c03f47bfeeb4a98b41($topDonors=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topDonors as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li>{$r['suffix']}  " . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donorName' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donorName($r) : '' ) . "</li>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicLink --*/
function topicLink($author) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['topicLink'] ) )
{
$count_d147dd691d74955a7ff2a82cb008b579 = is_array($this->functionData['topicLink']) ? count($this->functionData['topicLink']) : 0;
$this->functionData['topicLink'][$count_d147dd691d74955a7ff2a82cb008b579]['author'] = $author;
}
$IPBHTML .= "" . (($author['donate_donations'] > 0) ? ("<br />
<a class='ipsBadge ipsBadge_green'href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_donations&amp;member_id={$author['member_id']}", "public",'' ), "view_donations", "view_donations" ) . "\" title='" . $this->registry->getClass('class_localization')->formatNumber( $author['donate_donations'] ) . " {$this->lang->words['member_donations']}'>{$this->lang->words['donator']}</a><br /><br />
") : ("")) . "";
return $IPBHTML;
}

/* -- totalStats --*/
function totalStats($stats) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate_external', $this->_funcHooks['totalStats'] ) )
{
$count_8fed857c6d435b6773951b2b693a83e2 = is_array($this->functionData['totalStats']) ? count($this->functionData['totalStats']) : 0;
$this->functionData['totalStats'][$count_8fed857c6d435b6773951b2b693a83e2]['stats'] = $stats;
}
$IPBHTML .= "<div class='ipsSideBlock'>
	<h3>{$this->lang->words['donation_statistics']}</h3>
        <div class='_sbcollapsable'>
{$this->lang->words['total_donation_amount']} - <strong>{$stats['currency_symbol']}" . (($this->settings['dt_include_fees']) ? ("" . $this->registry->getClass('class_localization')->formatNumber( $stats['total_donations']-$stats['total_fees'], 2 ) . "") : ("" . $this->registry->getClass('class_localization')->formatNumber( $stats['total_donations'], 2 ) . "")) . "</strong><br />
" . (($this->settings['dt_include_fees']) ? ("
{$this->lang->words['total_fees']} - <strong>{$stats['currency_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $stats['total_fees'], 2 ) . "</strong><br />
") : ("")) . "
" . (($stats['total_goals']) ? ("{$this->lang->words['total_goal_amount']} - <strong>{$stats['currency_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $stats['total_goals'], 2 ) . "</strong><br /><br />
{$this->lang->words['still_needed']} - <strong>" . (($stats['still_needed'] < 0) ? ("--") : ("{$stats['currency_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $stats['still_needed'], 2 ) . "")) . "</strong><br /><br />
 " . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donateGraph' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donateGraph($stats['status'], $goal['g_id'], '95%', '50px') : '' ) . "") : ("")) . "

" . (($this->memberData['g_dt_donate']) ? ("<br /><form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=display&amp;do=donate", "public",'' ), "", "" ) . "' method=\"post\">

" . (($this->settings['dt_disable_completed'] && ( $this->caches['donate_cache']['total_donations'] + $this->caches['donate_cache']['total_fees'] ) >= $this->caches['donate_cache']['total_goals']) ? (" 
     <strong>{$this->lang->words['goal_total_met']}</strong>
") : ("" . (($this->settings['dt_amounts']) ? ("
    <select name='amount'>
    ".$this->__f__6d37869fa7622f20200121634a2e0542($stats)."    </select>
    ") : ("
    <input type='text' id='enter_amount' name='amount' class='input_text' size='4' />
    <script type='text/javascript'>
    $('enter_amount').defaultize( \"5.00\" );
    </script>
    ")) . "
    
    <input type='submit' class='input_submit' value='{$this->lang->words['donate']}' />")) . "

</form>") : ("")) . "
        </div>
</div>";
return $IPBHTML;
}


function __f__6d37869fa7622f20200121634a2e0542($stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( explode(",", $this->settings['dt_amounts'] ) as $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <option value=\"{$value}\">{$value}</option>
    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- viewDonateInfo --*/
function viewDonateInfo() {
$IPBHTML = "";
$IPBHTML .= "" . (($this->request['module']=='ajax') ? ("
    <h3>{$this->lang->words['donation_information']}</h3>
") : ("
    <h3 class='maintitle'>{$this->lang->words['donation_information']}</h3>
")) . "
<div class='ipsBox table_wrap'>
<div class='ipsBox_container ipsPad_half'>
     {$this->lang->words['dt_donation_details']}
</div>
</div>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>