<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 0               */
/* CACHE FILE: Generated: Tue, 19 Jan 2016 05:37:47 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_help_0 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['helpShowSection'] = array('notajax','isajax','notajax');
$this->_funcHooks['helpShowTopics'] = array('helpfiles');


}

/* -- helpShowSection --*/
function helpShowSection($one_text="",$two_text="",$three_text="", $text) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_help', $this->_funcHooks['helpShowSection'] ) )
{
$count_760b13a380130334b35eff9128da317d = is_array($this->functionData['helpShowSection']) ? count($this->functionData['helpShowSection']) : 0;
$this->functionData['helpShowSection'][$count_760b13a380130334b35eff9128da317d]['one_text'] = $one_text;
$this->functionData['helpShowSection'][$count_760b13a380130334b35eff9128da317d]['two_text'] = $two_text;
$this->functionData['helpShowSection'][$count_760b13a380130334b35eff9128da317d]['three_text'] = $three_text;
$this->functionData['helpShowSection'][$count_760b13a380130334b35eff9128da317d]['text'] = $text;
}
$IPBHTML .= "" . ((!$this->request['xml']) ? ("
<div class='topic_controls'>
	<ul class='topic_buttons'>
		<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=help", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['help_back_list_title']}\">{$this->lang->words['help_return_list']}</a></li>
	</ul>
</div>
") : ("")) . "
" . (($this->request['xml']) ? ("
<br />
") : ("")) . "
" . ((!$this->request['xml']) ? ("
	<h1 class='ipsType_pagetitle'>{$one_text}: {$three_text}</h1>
") : ("
	<h1 class='ipsType_subtitle'>{$one_text}: {$three_text}</h1>
")) . "
<br />
<div class='row2 help_doc ipsPad bullets'>
	{$text}
</div>
<br />";
return $IPBHTML;
}

/* -- helpShowTopics --*/
function helpShowTopics($one_text="",$two_text="",$three_text="",$rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_help', $this->_funcHooks['helpShowTopics'] ) )
{
$count_fef4ce5684c59808995502ece9b9e632 = is_array($this->functionData['helpShowTopics']) ? count($this->functionData['helpShowTopics']) : 0;
$this->functionData['helpShowTopics'][$count_fef4ce5684c59808995502ece9b9e632]['one_text'] = $one_text;
$this->functionData['helpShowTopics'][$count_fef4ce5684c59808995502ece9b9e632]['two_text'] = $two_text;
$this->functionData['helpShowTopics'][$count_fef4ce5684c59808995502ece9b9e632]['three_text'] = $three_text;
$this->functionData['helpShowTopics'][$count_fef4ce5684c59808995502ece9b9e632]['rows'] = $rows;
}

if ( ! isset( $this->registry->templateStriping['help'] ) ) {
$this->registry->templateStriping['help'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("help", "0" ) . "
<p class='message unspecific'>{$two_text}</p>
<h2 class='maintitle'>{$this->lang->words['help_topics']}</h2>
<div class='generic_bar'></div>
<ol id='help_topics'>
		" . ((count($rows)) ? ("".$this->__f__d94c5b76b45098a841983ed4588f2d01($one_text,$two_text,$three_text,$rows)."	") : ("
		<li class='no_messages'>{$this->lang->words['no_help_topics']}</li>
	")) . "
</ol>";
return $IPBHTML;
}


function __f__d94c5b76b45098a841983ed4588f2d01($one_text="",$two_text="",$three_text="",$rows)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $rows as $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<li class='" .  IPSLib::next( $this->registry->templateStriping["help"] ) . " helpRow'>
			<h3><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=help&amp;do=01&amp;HID={$entry['id']}", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['help_read_document']}\">{$entry['title']}</a></h3>
			<p>
				{$entry['description']}
			</p>
		</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>