<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 6               */
/* CACHE FILE: Generated: Tue, 17 May 2016 20:43:25 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_tomchristian_6 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['tctc91_customOfflinePage'] = array('isGuest');


}

/* -- tctc91_customOfflinePage --*/
function tctc91_customOfflinePage() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_tomchristian', $this->_funcHooks['tctc91_customOfflinePage'] ) )
{
$count_ee40c9c72c2d68910bc9de2e7324ff36 = is_array($this->functionData['tctc91_customOfflinePage']) ? count($this->functionData['tctc91_customOfflinePage']) : 0;
}
$IPBHTML .= "<!-- Offline Pages by Tom Christian -->
" . (($this->settings['tcCustomOfflinePage_enabled'] == '1') ? ("<style type='text/css'>
  ::selection { background:rgba(0,0,0,0.5); color:#fff; }
  ::-moz-selection { background:rgba(0,0,0,0.5); color:#fff; }

  body,html{
    background: black !important;
    margin-top: 0 !important;
    height:100%;
    font-family: helvetica, arial;
  }

  #footer_utilities { display: none; }

  #offlineBackground {
    background: black url({$this->settings['css_base_url']}style_extra/tctc91_customOfflinePage/img/{$this->settings['tcCustomOfflinePage_bg']}.jpg) no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
    filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{$this->settings['css_base_url']}style_extra/tctc91_customOfflinePage/img/bg1.jpg', sizingMethod='scale');
    -ms-filter: \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='{$this->settings['css_base_url']}style_extra/tctc91_customOfflinePage/img/bg1.jpg', sizingMethod='scale')\";
    color: white;
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
  }

  .offlineInner {
    text-align: center;
    height:450px;
    position:absolute;
    left:50%;
    top:50%;
    position: initial;
    margin: 100px auto 0;
    width: 100%;
  }

  .offlineInner { text-shadow: 1px 2px 2px rgba(0,0,0,0.1); }
  .offlineInner p { line-height: initial; }

  #offlineBackground .ipsButton {
    -moz-border-radius: 2px;
    -webkit-border-radius: 2px;
    border-radius: 2px;
    -moz-background-clip: padding;
    -webkit-background-clip: padding-box;
    background-clip: padding-box;
    background-color: #282828;
    -moz-box-shadow: 0 3px 0 #000;
    -webkit-box-shadow: 0 3px 0 #000;
    box-shadow: 0 3px 0 #000;
    background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEwMCAxMDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjxsaW5lYXJHcmFkaWVudCBpZD0iaGF0MCIgZ3JhZGllbnRVbml0cz0ib2JqZWN0Qm91bmRpbmdCb3giIHgxPSI1MCUiIHkxPSIxMDAlIiB4Mj0iNTAlIiB5Mj0iLTEuNDIxMDg1NDcxNTIwMmUtMTQlIj4KPHN0b3Agb2Zmc2V0PSIwJSIgc3RvcC1jb2xvcj0iIzIxMjEyMSIgc3RvcC1vcGFjaXR5PSIxIi8+CjxzdG9wIG9mZnNldD0iMTAwJSIgc3RvcC1jb2xvcj0iIzJlMmUyZSIgc3RvcC1vcGFjaXR5PSIxIi8+CiAgIDwvbGluZWFyR3JhZGllbnQ+Cgo8cmVjdCB4PSIwIiB5PSIwIiB3aWR0aD0iMTAwIiBoZWlnaHQ9IjEwMCIgZmlsbD0idXJsKCNoYXQwKSIgLz4KPC9zdmc+);
    background-image: -moz-linear-gradient(bottom, #212121 0%, #2e2e2e 100%);
    background-image: -o-linear-gradient(bottom, #212121 0%, #2e2e2e 100%);
    background-image: -webkit-linear-gradient(bottom, #212121 0%, #2e2e2e 100%);
    background-image: linear-gradient(bottom, #212121 0%, #2e2e2e 100%);
    border: 0;
    color: #fff;
    text-shadow: none;
    font-size: 19px;
    font-family: inherit;
    line-height: 30px;
    padding: 20px 30px;
    text-align: center;
    min-width: 250px;
    display: inline-block;
    cursor: pointer;
    margin-top: 37px;
  }
  #offlineBackground .ipsButton:active {
    background: #222;
    -moz-box-shadow: 0 1px 0 rgba(255,255,255,.3);
    -webkit-box-shadow: 0 1px 0 rgba(255,255,255,.3);
    box-shadow: 0 1px 0 rgba(255,255,255,.3);
    margin-top: 40px;
  }
  </style>
  <div id=\"offlineBackground\">
    <div class=\"offlineInner\">
      {$this->settings['tcCustomOfflinePage_message']}
      <p>
      " . ((!$this->memberData['member_id']) ? ("
        <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login", "public",'' ), "", "" ) . "' title='{$this->lang->words['attempt_login']}' class='ipsButton'>{$this->lang->words['click_login']}</a>
      ") : ("
        <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=login&amp;do=logout&amp;k={$this->member->form_hash}", "public",'' ), "", "" ) . "' title='{$this->lang->words['log_out']}' class='ipsButton'>{$this->lang->words['log_out']}</a>
      ")) . "
      </p>
    </div>
  </div>") : ("")) . "";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>