<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 6               */
/* CACHE FILE: Generated: Tue, 17 May 2016 20:43:23 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_donate_6 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['donateSetup'] = array('currencySelected','currencies','goalSelected','goals','gatewaySelected','gateways','guestNotice','showGoalOptions');
$this->_funcHooks['donateSetupSend'] = array('guestNotice','hasGoal');
$this->_funcHooks['splashPage'] = array('privateGoalStatus','lifetime_goal','privateGoalAmount','privateGoalDonated','goal_row','goal_link','has_note','donation_row','has_goals','viewGoalPerms','latest_donations','viewDonationPerms');
$this->_funcHooks['statsBox'] = array('calculateFee','showTotalFees','donationsFull','showGoalStats','viewDonationPerms','viewGoalLink','activeNames');
$this->_funcHooks['topMenu'] = array('currentDonor','amount_dropdown','showDonateBox','makeDonationPerms');
$this->_funcHooks['viewAllDonations'] = array('goal_link','has_note','donation_row','per_page_selected','sort_by_date','sort_by_member_name','sort_by_amount','sort_by_goal','sort_order_desc','sort_order_asc');
$this->_funcHooks['viewAllGoals'] = array('privateGoalStatus','lifetime_goal','privateGoalAmount','privateGoalDonated','goal_row','per_page_selected','sort_by_g_start_date','sort_by_g_end_date','sort_by_g_name','sort_by_views','sort_by_g_amount','sort_by_donations','sort_order_desc','sort_order_asc');
$this->_funcHooks['viewAllTopDonors'] = array('donation_row');
$this->_funcHooks['viewGoal'] = array('has_note','donation_row','privateGoalStatus','lifetime_goal','privateGoalAmount','privateGoalDonated','latest_donations');


}

/* -- donateSetup --*/
function donateSetup($donation=array(), $goals=array(), $currencies=array(), $gateways=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['donateSetup'] ) )
{
$count_b672a666c8ba35b8c590f3e1e7a787a3 = is_array($this->functionData['donateSetup']) ? count($this->functionData['donateSetup']) : 0;
$this->functionData['donateSetup'][$count_b672a666c8ba35b8c590f3e1e7a787a3]['donation'] = $donation;
$this->functionData['donateSetup'][$count_b672a666c8ba35b8c590f3e1e7a787a3]['goals'] = $goals;
$this->functionData['donateSetup'][$count_b672a666c8ba35b8c590f3e1e7a787a3]['currencies'] = $currencies;
$this->functionData['donateSetup'][$count_b672a666c8ba35b8c590f3e1e7a787a3]['gateways'] = $gateways;
}
$IPBHTML .= "<div class='ipsSteps clearfix'>
<ul>		
	<li class='ipsSteps_active'>
		<strong class='ipsSteps_title'>{$this->lang->words['step_one']}</strong>
		<span class='ipsSteps_desc'>{$this->lang->words['donation_details']}</span>
		<span class='ipsSteps_arrow'>&nbsp;</span>

	</li>
	<li class=''>
		<strong class='ipsSteps_title'>{$this->lang->words['step_two']}</strong>
		<span class='ipsSteps_desc'>{$this->lang->words['payment_processor']}</span>
		<span class='ipsSteps_arrow'>&nbsp;</span>
	</li>
</ul>
</div>
	
<div class='ipsBox'>		
<div class='ipsBox_container ipsPad'>

<form id='donate_setup' action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=display&amp;do=donate_send", "public",'' ), "", "" ) . "' method=\"post\">
<input type='hidden' name='amount' value='{$donation['amount']}' />

<div class='post_form'>	

" . ((!$this->memberData['member_id']) ? ("
<div class='message error'>{$this->lang->words['donate_guest_warning']}</div><br />
") : ("")) . "

<fieldset>
<ul>
<li class='field'>
	<label for='name'><strong>{$this->lang->words['your_name']}</strong></label>
	{$this->memberData['members_display_name']}
</li>
<li class='field'>
	<label for='currency'><strong>{$this->lang->words['amount']}</strong></label>
	{$donation['amount']}
        <select id='currency' name='currency' class='input_select'>
	".$this->__f__fd87d77b143b0df06e54389e3ee1d63d($donation,$goals,$currencies,$gateways)."        </select>
</li>
" . ((is_array( $goals ) AND count( $goals )) ? ("
<li class='field'>
	<label for='goal'><strong>{$this->lang->words['goal']}</strong></label>
        <select id='goal' name='goal' class='input_select'>
	".$this->__f__ec0fff7473efe612c52f5adaa05f1035($donation,$goals,$currencies,$gateways)."        </select>
	<span class='desc'>{$this->lang->words['goal_info']}</span>
</li>
") : ("")) . "
<li class='field'>
	<label for='gateway'><strong>{$this->lang->words['payment_processor']}</strong></label>
        <select id='gateway' name='gateway' class='input_select'>
	".$this->__f__1a33e6b7035111f8bd72a27de8adf0f8($donation,$goals,$currencies,$gateways)."        </select>
	<span class='desc'>{$this->lang->words['payment_processor_desc']}</span>
</li>

</ul>

</fieldset>

<fieldset class='submit'>
<input class='input_submit' type=\"submit\" name=\"Submit\" value=\"{$this->lang->words['next_step']}\" /> 
{$this->lang->words['or']} 
<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate", "public",'' ), "app=donate", "app=donate" ) . "' title='{$this->lang->words['cancel']}'>{$this->lang->words['cancel']}</a>
		
</fieldset>

</div>

</form>

</div>
</div>";
return $IPBHTML;
}


function __f__fd87d77b143b0df06e54389e3ee1d63d($donation=array(), $goals=array(), $currencies=array(), $gateways=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $currencies as $currency )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<option value='{$currency['c_id']}'" . (($currency['c_id']==$donation['currency']) ? (" selected='selected'") : ("")) . ">{$currency['c_name']}</option>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__ec0fff7473efe612c52f5adaa05f1035($donation=array(), $goals=array(), $currencies=array(), $gateways=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $goals as $goal )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<option value='{$goal['g_id']}'" . (($goal['g_id']==$donation['goal']) ? (" selected='selected'") : ("")) . ">{$goal['g_name']}</option>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__1a33e6b7035111f8bd72a27de8adf0f8($donation=array(), $goals=array(), $currencies=array(), $gateways=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $gateways as $gateway )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<option value='{$gateway['gw_id']}'" . (($gateway['gw_id']==$donation['gateway_id']) ? (" selected='selected'") : ("")) . ">{$gateway['gw_name']}</option>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- donateSetupSend --*/
function donateSetupSend($donation=array(), $gateway=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['donateSetupSend'] ) )
{
$count_f2df80c85812a17853002dc52cb0afc9 = is_array($this->functionData['donateSetupSend']) ? count($this->functionData['donateSetupSend']) : 0;
$this->functionData['donateSetupSend'][$count_f2df80c85812a17853002dc52cb0afc9]['donation'] = $donation;
$this->functionData['donateSetupSend'][$count_f2df80c85812a17853002dc52cb0afc9]['gateway'] = $gateway;
}
$IPBHTML .= "<div class='ipsSteps clearfix'>
<ul>		
	<li>
		<strong class='ipsSteps_title'>{$this->lang->words['step_one']}</strong>
		<span class='ipsSteps_desc'>{$this->lang->words['donation_details']}</span>
		<span class='ipsSteps_arrow'>&nbsp;</span>

	</li>
	<li class='ipsSteps_active'>
		<strong class='ipsSteps_title'>{$this->lang->words['step_two']}</strong>
		<span class='ipsSteps_desc'>{$this->lang->words['payment_processor']}</span>
		<span class='ipsSteps_arrow'>&nbsp;</span>
	</li>
</ul>
</div>
	
<div class='ipsBox'>		
<div class='ipsBox_container ipsPad'>

<div class='post_form'>	

" . ((!$this->memberData['member_id']) ? ("
<div class='message error'>{$this->lang->words['donate_guest_warning']}</div><br />
") : ("")) . "

<fieldset>
<ul>
<li class='field'>
	<label for='name'><strong>{$this->lang->words['your_name']}</strong></label>
	{$this->memberData['members_display_name']}
</li>
<li class='field'>
	<label for='currency'><strong>{$this->lang->words['amount']}</strong></label>
	{$donation['currency_symbol']}{$donation['amount']}        
</li>
" . (($donation['goal_name']) ? ("
<li class='field'>
	<label for='goal'><strong>{$this->lang->words['goal']}</strong></label>
        {$donation['goal_name']}

</li>
") : ("")) . "
<li class='field'>
	<label for='gateway'><strong>{$this->lang->words['payment_processor']}</strong></label>
        {$gateway['gw_name']}

</li>

</ul>

<div class='ipsPad' style='text-align:center;'>
{$gateway['gw_summary']}<br />{$gateway['html']}
</div>

</fieldset>

<fieldset class='submit'>
<< <a href=\"javascript:history.go(-1)\" title='{$this->lang->words['go_back']}'>{$this->lang->words['go_back']}</a>		
</fieldset>

</div>

</div>
</div>";
return $IPBHTML;
}

/* -- splashPage --*/
function splashPage($goals=array(), $donations=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['splashPage'] ) )
{
$count_968aaedb27146add7e160ffb237d4232 = is_array($this->functionData['splashPage']) ? count($this->functionData['splashPage']) : 0;
$this->functionData['splashPage'][$count_968aaedb27146add7e160ffb237d4232]['goals'] = $goals;
$this->functionData['splashPage'][$count_968aaedb27146add7e160ffb237d4232]['donations'] = $donations;
}
$IPBHTML .= "" . (($this->memberData['g_dt_view_goals']) ? ("" . ((is_array($goals) AND count($goals)) ? ("

<div class='category_block block_wrap'>
<h3 class='maintitle'>{$this->lang->words['current_goals']}</h3>
<div class='ipsBox table_wrap'>
<div class='ipsBox_container'>
<table class='ipb_table' summary=\"{$this->lang->words['current_goals']}\">
<tr class='header hide'>
<th scope='col' class='col_c_icon'></th>
<th scope='col' class='col_c_forum'>{$this->lang->words['goal_name']}</th>
<th scope='col' class='col_c_stats stats'>{$this->lang->words['status']}</th>
<th scope='col' class='col_c_stats stats'>{$this->lang->words['stats']}</th>
</tr>".$this->__f__9acf720938810cc7ab4b6f7071fc2264($goals,$donations)."</tr>
</table>
</div>
</div>
</div>

") : ("")) . "") : ("")) . "

<br class='clear' />

" . (($this->memberData['g_dt_view_donations']) ? ("" . ((is_array($donations) AND count($donations)) ? ("

<div class='category_block block_wrap'>
<h3 class='maintitle'>{$this->lang->words['latest_donations']}</h3>
<div class='ipsBox table_wrap'>
<div class='ipsBox_container'>
<table class='ipb_table' summary=\"{$this->lang->words['latest_donations']}\">
<tr class='header'>
<th scope='col' class='short'>{$this->lang->words['donor_name']}</th>
<th scope='col' class='short'>{$this->lang->words['goal_donated']}</th>
<th scope='col' >{$this->lang->words['donation_note']}</th>
<th scope='col' class='short'>{$this->lang->words['amount']}</th>
</tr>".$this->__f__990312091d3bb4f67c1078975bd6da23($goals,$donations)."</tr>
</table>
</div>
</div>
</div>

") : ("")) . "") : ("")) . "";
return $IPBHTML;
}


function __f__9acf720938810cc7ab4b6f7071fc2264($goals=array(), $donations=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $goals as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<tr class='col_c_forum'>
	<td class='altrow short' style='width:7%;'>
        " . (($r['g_private']) ? ("--") : ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donateGraph' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donateGraph($r['status'], $r['g_id'], '95%', '30px') : '' ) . "")) . "
	</td>
	<td>
	<h4><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=display&amp;section=donations&amp;do=view_goal&amp;id={$r['g_id']}", "publicWithApp",'' ), "{$r['seo_name']}", "view_goal" ) . "'>{$r['g_name']}</a></h4>
	<p class='desc'>{$r['g_desc']}</p>	
        <span class='date'>{$this->lang->words['goal_runtime']}: " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['g_start_date'],"long", 0)) . " - " . (($r['g_forever']) ? ("{$this->lang->words['continuous_goal']}") : ("" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['g_end_date'],"long", 0)) . "")) . "</span>			
	
</td>
<td class='altrow stats'>

<ul>
<li>" . (($r['g_private']) ? ("--") : ("{$this->lang->words['goal']} {$r['c_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $r['g_amount'], 2 ) . "")) . "</li>
<li>" . (($r['g_private']) ? ("--") : ("{$this->lang->words['received']} {$r['c_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $r['g_received'], 2 ) . "")) . "</li>				
</ul>

</td>
<td class='stats'>

<ul>
<li>" . intval($r['donations']) . " {$this->lang->words['donations']}</li>
<li>" . intval($r['views']) . " {$this->lang->words['views']}</li>				
</ul>

</td>	
			
</tr>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__990312091d3bb4f67c1078975bd6da23($goals=array(), $donations=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $donations as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
<tr>
<td class='col_c_post'>
     " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($r['member']) : '' ) . " 

     <ul class=\"last_post ipsType_small\">
          <li class='desc'>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donorName' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donorName($r) : '' ) . "</li>
          <li class='desc lighter'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['date'],"long", 0)) . "</li>
     </ul>
</td>

<td class='short'>" . (($r['g_id']) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=display&amp;section=donations&amp;do=view_goal&amp;id={$r['g_id']}", "publicWithApp",'' ), "{$r['seo_name']}", "view_goal" ) . "'>{$r['g_name']}</a>") : ("{$this->lang->words['not_available']}")) . "</td>
<td class='altrow'>" . (($r['note']) ? ("{$r['note']}") : ("<i>{$this->lang->words['no_note']}</i>")) . "</td>
<td class='altrow short'><strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donationAmount' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donationAmount($r) : '' ) . "</strong></td>			
</tr>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statsBox --*/
function statsBox($topDonors=array(), $stats=array(), $active='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['statsBox'] ) )
{
$count_00d7b8e76be71de7368d3cd5f1c0561e = is_array($this->functionData['statsBox']) ? count($this->functionData['statsBox']) : 0;
$this->functionData['statsBox'][$count_00d7b8e76be71de7368d3cd5f1c0561e]['topDonors'] = $topDonors;
$this->functionData['statsBox'][$count_00d7b8e76be71de7368d3cd5f1c0561e]['stats'] = $stats;
$this->functionData['statsBox'][$count_00d7b8e76be71de7368d3cd5f1c0561e]['active'] = $active;
}
$IPBHTML .= "<br class='clear' />
	<div id='board_stats'>		
		<ul class='ipsType_small ipsList_inline'>
			<li class='clear'>
				<span class='value' data-tooltip=\"{$stats['status']}%\">{$stats['currency_symbol']}" . (($this->settings['dt_include_fees']) ? ("" . $this->registry->getClass('class_localization')->formatNumber( $stats['total_donations']-$stats['total_fees'], 2 ) . "") : ("" . $this->registry->getClass('class_localization')->formatNumber( $stats['total_donations'], 2 ) . "")) . "</span>
				{$this->lang->words['total_donations']}
			</li>
" . (($this->settings['dt_include_fees']) ? ("
			<li class='clear'>
				<span class='value'>{$stats['currency_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $stats['total_fees'], 2 ) . "</span>
				{$this->lang->words['total_fees']}
			</li>
") : ("")) . "
" . (($stats['total_goals']) ? ("<li class='clear'>
				<span class='value'>{$stats['currency_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $stats['total_goals'], 2 ) . "</span>
				{$this->lang->words['total_goals']}
			</li>
			<li class='clear'>
				<span class='value'>" . (($stats['still_needed'] < 0) ? ("--") : ("{$stats['currency_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $stats['still_needed'], 2 ) . "")) . "</span>
				{$this->lang->words['still_needed']}
			</li>") : ("")) . "
		</ul>
	</div>

<div id='board_statistics' class='statistics clearfix'>
	<ul id='stat_links' class='ipsList_inline right ipsType_small'>
                  " . (($this->memberData['g_dt_view_donations']) ? ("
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_donations", "public",'' ), "view_donations", "view_donations" ) . "\">{$this->lang->words['view_all_donations']}</a></li>
                  ") : ("")) . "
                  " . (($this->memberData['g_dt_view_goals'] AND $stats['total_goals']) ? ("
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_goals", "public",'' ), "view_goals", "view_goals" ) . "\">{$this->lang->words['view_all_goals']}</a></li>
                  ") : ("")) . "
			<li><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_top_donors", "public",'' ), "view_top_donors", "view_top_donors" ) . "\">{$this->lang->words['view_top_donors']}</a></li>
	</ul>
	
	<h4 class='statistics_head'>{$active['TOTAL']} {$this->lang->words['active_users']}</h4>
	<p class='statistics_brief desc'>
		{$active['MEMBERS']} {$this->lang->words['stats_members']}, {$active['GUESTS']} {$this->lang->words['stats_guests']}, {$active['ANON']} {$this->lang->words['stats_anonymous_users']}
	</p>
	
	" . ((count($active['NAMES'])) ? ("
		<br />
		<p>
		<span class='name'>" . implode( ",</span> <span class='name'>", $active['NAMES']) . "</span>					
		</p>
	") : ("")) . "
</div>";
return $IPBHTML;
}

/* -- topMenu --*/
function topMenu() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['topMenu'] ) )
{
$count_529a867107248ec6dcd26649a2c2ec01 = is_array($this->functionData['topMenu']) ? count($this->functionData['topMenu']) : 0;
}
$IPBHTML .= "<div class='message clear clearfix'>
" . (($this->memberData['donate_donations']) ? ("
" . str_replace( "<#EXTRA#>", $this->memberData['donate_donations'], $this->lang->words['donate_thank_you'] ) . "
<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_donations&amp;members_display_name={$this->memberData['members_display_name']}", "public",'' ), "view_donations", "view_donations" ) . "\">{$this->lang->words['here']}</a>") : ("{$this->lang->words['member_donate_message']} <a href='#' id='donate_info'>{$this->lang->words['read_more']}</a>")) . "

" . (($this->memberData['g_dt_donate']) ? ("<div class='right'>
<form id='donate_form' action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=display&amp;do=donate", "public",'' ), "", "" ) . "' method=\"post\">

" . (($this->settings['dt_disable_completed'] && ( $this->caches['donate_cache']['total_donations'] + $this->caches['donate_cache']['total_fees'] ) >= $this->caches['donate_cache']['total_goals']) ? (" 
     <strong>{$this->lang->words['goal_total_met']}</strong>
") : ("" . (($this->settings['dt_amounts']) ? ("
    <strong>{$this->lang->words['select_amount_text']}</strong> <select name='amount'>
    ".$this->__f__0f03ebc6fb4fdea11c0352a0c9ba3d99()."    </select>
    ") : ("
    <strong>{$this->lang->words['enter_amount_text']}</strong>&nbsp;&nbsp;<input type='text' id='enter_amount' name='amount' class='input_text' size='4' />
    <script type='text/javascript'>
    $('enter_amount').defaultize( \"5.00\" );
    </script>
    ")) . "
    <input type='submit' class='input_submit' value='{$this->lang->words['donate_now']}' />")) . "

</form>
</div>") : ("")) . "
</div><br />";
return $IPBHTML;
}


function __f__0f03ebc6fb4fdea11c0352a0c9ba3d99()
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( explode(",", $this->settings['dt_amounts'] ) as $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <option value=\"{$value}\">{$value}</option>
    
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- viewAllDonations --*/
function viewAllDonations($donations=array(), $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['viewAllDonations'] ) )
{
$count_0042e8bb3b37cd2668ea2337443c1fd6 = is_array($this->functionData['viewAllDonations']) ? count($this->functionData['viewAllDonations']) : 0;
$this->functionData['viewAllDonations'][$count_0042e8bb3b37cd2668ea2337443c1fd6]['donations'] = $donations;
$this->functionData['viewAllDonations'][$count_0042e8bb3b37cd2668ea2337443c1fd6]['pages'] = $pages;
}
$IPBHTML .= "<div class='category_block block_wrap'>
<h3 class='maintitle'>{$this->lang->words['view_all_donations']}</h3>
<div class='ipsBox table_wrap'>
<div class='ipsBox_container'>
<table class='ipb_table' summary=\"{$this->lang->words['view_all_donations']}\">
<tr class='header'>
<th scope='col' class='short'>{$this->lang->words['donor_name']}</th>
<th scope='col' class='short'>{$this->lang->words['goal_donated']}</th>
<th scope='col' >{$this->lang->words['donation_note']}</th>
<th scope='col' class='short'>{$this->lang->words['amount']}</th>
</tr>".$this->__f__825a299bd11f0687af46fcacd4476e0b($donations,$pages)."</tr>
</table>
</div>
</div>
</div>

<div class='moderation_bar rounded with_action'>
<form id='search_box' method=\"post\" action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_donations", "public",'' ), "view_donations", "view_donations" ) . "\">
<fieldset>
{$this->lang->words['search_donate_text']}&nbsp;&nbsp;<input type='text' id='members_display_name' name='members_display_name' value='{$this->request['members_display_name']}' class='input_text' size='30' /> <input type='submit' class='input_submit' value='{$this->lang->words['search']}' />
</fieldset>
</form>
</div>

<div id='search_filter' class='filter_bar rounded'>
<span id='show_filter' class='clickable'>{$this->lang->words['show_filter_options']}</span>

<form id='filter_form' action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_donations", "public",'' ), "view_donations", "view_donations" ) . "' method=\"post\">
		
<fieldset>

<label for='sort_by'>{$this->lang->words['sort_by']}</label>&nbsp; <select name=\"sort_by\" id='sort_by' class='input_select'>
<option value=\"date\" " . (($this->request['sort_by'] == 'date') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['donation_date']}</option>
<option value=\"member_name\" " . (($this->request['sort_by'] == 'member_name') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['member_name']}</option>
<option value=\"amount\" " . (($this->request['sort_by'] == 'amount') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['amount']}</option>
<option value=\"goal\" " . (($this->request['sort_by'] == 'goal') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['goal']}</option>
</select>

<label for='sort_order'>{$this->lang->words['sort_order']}</label>&nbsp; <select name=\"sort_order\" id='sort_how' class='input_select'>
<option value=\"desc\" " . (($this->request['sort_order'] == 'desc' OR $this->request['sort_order'] == 'DESC') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['descending']}</option>
<option value=\"asc\" " . (($this->request['sort_order'] == 'asc' OR $this->request['sort_order'] == 'ASC') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['ascending']}</option>
</select>
					
<label for='per_page'>{$this->lang->words['results_per_page']} </label>&nbsp; <select name=\"per_page\" id='per_page' class='input_select'>".$this->__f__b4d7c00699680801f3437e8acdb1fe7e($donations,$pages)."</select>

<input type=\"submit\" value=\"{$this->lang->words['submit']}\" class=\"input_submit alt\" />
</fieldset>
</form>

<script type='text/javascript'>
if( $('filter_form' ) )
{
	$('filter_form').hide();
	$('show_filter').show();
}
</script>

</div>

{$pages}";
return $IPBHTML;
}


function __f__825a299bd11f0687af46fcacd4476e0b($donations=array(), $pages)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $donations as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
<tr>
<td class='col_c_post'>
     " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($r['member']) : '' ) . " 

     <ul class=\"last_post ipsType_small\">
          <li class='desc'>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donorName' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donorName($r) : '' ) . "</li>
          <li class='desc lighter'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['date'],"long", 0)) . "</li>
     </ul>
</td>

<td class='short'>" . (($r['g_id']) ? ("<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=display&amp;section=donations&amp;do=view_goal&amp;id={$r['g_id']}", "publicWithApp",'' ), "{$r['seo_name']}", "view_goal" ) . "'>{$r['g_name']}</a>") : ("{$this->lang->words['not_available']}")) . "</td>
<td class='altrow'>" . (($r['note']) ? ("{$r['note']}") : ("<i>{$this->lang->words['no_note']}</i>")) . "</td>
<td class='altrow short'><strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donationAmount' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donationAmount($r) : '' ) . "</strong></td>			
</tr>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__b4d7c00699680801f3437e8acdb1fe7e($donations=array(), $pages)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( explode(",", "5,10,25,50" ) as $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
<option value=\"{$value}\" " . (($value == $this->request['per_page']) ? ("selected=\"selected\"") : ("")) . ">{$value}</option>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- viewAllGoals --*/
function viewAllGoals($goals=array(), $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['viewAllGoals'] ) )
{
$count_2d5af0c8653d961d17831fceb450b2cd = is_array($this->functionData['viewAllGoals']) ? count($this->functionData['viewAllGoals']) : 0;
$this->functionData['viewAllGoals'][$count_2d5af0c8653d961d17831fceb450b2cd]['goals'] = $goals;
$this->functionData['viewAllGoals'][$count_2d5af0c8653d961d17831fceb450b2cd]['pages'] = $pages;
}
$IPBHTML .= "<div class='category_block block_wrap'>
<h3 class='maintitle'>{$this->lang->words['view_all_goals']}</h3>
<div class='ipsBox table_wrap'>
<div class='ipsBox_container'>
<table class='ipb_table' summary=\"{$this->lang->words['view_all_goals']}\">
<tr class='header hide'>
<th scope='col' class='col_c_icon'></th>
<th scope='col' class='col_c_forum'>{$this->lang->words['goal_name']}</th>
<th scope='col' class='col_c_stats stats'>{$this->lang->words['status']}</th>
<th scope='col' class='col_c_stats stats'>{$this->lang->words['stats']}</th>
</tr>".$this->__f__be2bf3a5124a8a71669ca178fca9aec1($goals,$pages)."</tr>
</table>
</div>
</div>
</div>

<br class='clear' />

<div id='search_filter' class='filter_bar rounded'>
<span id='show_filter' class='clickable'>{$this->lang->words['show_filter_options']}</span>

<form id='filter_form' action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=donate&amp;module=display&amp;section=donations&amp;do=view_goals", "public",'' ), "view_goals", "view_goals" ) . "' method=\"post\">
		
<fieldset>

<label for='sort_by'>Sort By</label>&nbsp; <select name=\"sort_by\" id='sort_by' class='input_select'>
<option value=\"g_start_date\" " . (($this->request['sort_by'] == 'g_start_date') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['start_date']}</option>
<option value=\"g_end_date\" " . (($this->request['sort_by'] == 'g_end_date') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['end_date']}</option>
<option value=\"g_name\" " . (($this->request['sort_by'] == 'g_name') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['goal_name']}</option>
<option value=\"views\" " . (($this->request['sort_by'] == 'views') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['views']}</option>
<option value=\"g_amount\" " . (($this->request['sort_by'] == 'g_amount') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['amount']}</option>
<option value=\"donations\" " . (($this->request['sort_by'] == 'donations') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['donations']}</option>
</select>

<label for='sort_order'>{$this->lang->words['sort_order']}</label>&nbsp; <select name=\"sort_order\" id='sort_how' class='input_select'>
<option value=\"desc\" " . (($this->request['sort_order'] == 'desc' OR $this->request['sort_order'] == 'DESC') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['descending']}</option>
<option value=\"asc\" " . (($this->request['sort_order'] == 'asc' OR $this->request['sort_order'] == 'ASC') ? ("selected=\"selected\"") : ("")) . ">{$this->lang->words['ascending']}</option>
</select>
					
<label for='per_page'>{$this->lang->words['results_per_page']} </label>&nbsp; <select name=\"per_page\" id='per_page' class='input_select'>".$this->__f__b6bf6f7e7e055e25ec4c661a1bba798f($goals,$pages)."</select>

<input type=\"submit\" value=\"{$this->lang->words['submit']}\" class=\"input_submit alt\" />
</fieldset>
</form>

<script type='text/javascript'>
if( $('filter_form' ) )
{
	$('filter_form').hide();
	$('show_filter').show();
}
</script>

</div>

{$pages}";
return $IPBHTML;
}


function __f__be2bf3a5124a8a71669ca178fca9aec1($goals=array(), $pages)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $goals as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<tr class='col_c_forum'>
	<td class='altrow short' style='width:7%;'>
        " . (($r['g_private']) ? ("--") : ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donateGraph' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donateGraph($r['status'], $r['g_id'], '95%', '30px') : '' ) . "")) . "
	</td>
	<td>
	<h4><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "module=display&amp;section=donations&amp;do=view_goal&amp;id={$r['g_id']}", "publicWithApp",'' ), "{$r['seo_name']}", "view_goal" ) . "'>{$r['g_name']}</a></h4>
	<p class='desc'>{$r['g_desc']}</p>	
        <span class='date'>{$this->lang->words['goal_runtime']}: " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['g_start_date'],"long", 0)) . " - " . (($r['g_forever']) ? ("{$this->lang->words['continuous_goal']}") : ("" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['g_end_date'],"long", 0)) . "")) . "</span>			
	
</td>
<td class='altrow stats'>
<ul>
<li>" . (($r['g_private']) ? ("--") : ("{$this->lang->words['goal']} {$r['c_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $r['g_amount'], 2 ) . "")) . "</li>
<li>" . (($r['g_private']) ? ("--") : ("{$this->lang->words['received']} {$r['c_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $r['g_received'], 2 ) . "")) . "</li>				
</ul>

</td>
<td class='stats'>

<ul>
<li>" . intval($r['donations']) . " {$this->lang->words['donations']}</li>
<li>" . intval($r['views']) . " {$this->lang->words['views']}</li>				
</ul>

</td>	
			
</tr>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__b6bf6f7e7e055e25ec4c661a1bba798f($goals=array(), $pages)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( explode(",", "5,10,25,50" ) as $value )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
<option value=\"{$value}\" " . (($value == $this->request['per_page']) ? ("selected=\"selected\"") : ("")) . ">{$value}</option>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- viewAllTopDonors --*/
function viewAllTopDonors($donors=array(), $pages) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['viewAllTopDonors'] ) )
{
$count_f5e48486d5a0c0a8271f79a1d3a0d690 = is_array($this->functionData['viewAllTopDonors']) ? count($this->functionData['viewAllTopDonors']) : 0;
$this->functionData['viewAllTopDonors'][$count_f5e48486d5a0c0a8271f79a1d3a0d690]['donors'] = $donors;
$this->functionData['viewAllTopDonors'][$count_f5e48486d5a0c0a8271f79a1d3a0d690]['pages'] = $pages;
}
$IPBHTML .= "<div class='category_block block_wrap'>
<h3 class='maintitle'>{$this->lang->words['view_top_donors']}</h3>
<div class='ipsBox table_wrap'>
<div class='ipsBox_container'>
<table class='ipb_table' summary=\"{$this->lang->words['view_top_donors']}\">
<tr class='header'>
<th scope='col' class='short' style='width:5%;'>#</th>
<th scope='col' class='short'>{$this->lang->words['donor_name']}</th>
<th scope='col' class='short'>{$this->lang->words['total_amount']}</th>
</tr>".$this->__f__c1fda03c28e419d262ce4474e43effbe($donors,$pages)."</tr>
</table>
</div>
</div>
</div>

{$pages}";
return $IPBHTML;
}


function __f__c1fda03c28e419d262ce4474e43effbe($donors=array(), $pages)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $donors as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<tr>
	<td class='altrow short'><strong>{$r['count']}</strong></td>

<td class='short'>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donorName' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donorName($r) : '' ) . "</td>		
<td class='short altrow'>{$r['c_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $r['total_amount'], 2 ) . "</td>
</tr>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- viewGoal --*/
function viewGoal($goal=array(), $donations=array(), $pages='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_donate', $this->_funcHooks['viewGoal'] ) )
{
$count_00e19043714d20458a15dee62d5a61b9 = is_array($this->functionData['viewGoal']) ? count($this->functionData['viewGoal']) : 0;
$this->functionData['viewGoal'][$count_00e19043714d20458a15dee62d5a61b9]['goal'] = $goal;
$this->functionData['viewGoal'][$count_00e19043714d20458a15dee62d5a61b9]['donations'] = $donations;
$this->functionData['viewGoal'][$count_00e19043714d20458a15dee62d5a61b9]['pages'] = $pages;
}
$IPBHTML .= "<div class='category_block block_wrap'>
<h3 class='maintitle'>{$goal['g_name']}</h3>
<div class='ipsBox table_wrap'>
<div class='ipsBox_container'>
<table class='ipb_table'>
	<tr class='row1'>
	<td class='altrow short' style='width:7%;'>
        " . (($goal['g_private']) ? ("--") : ("" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donateGraph' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donateGraph($goal['status'], $r['g_id'], '95%', '30px') : '' ) . "")) . "
	</td>
	<td>
	<p class='desc'>{$goal['g_desc']}</p>	
        <span class='date'>{$this->lang->words['goal_runtime']}: " . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($goal['g_start_date'],"long", 0)) . " - " . (($goal['g_forever']) ? ("{$this->lang->words['continuous_goal']}") : ("" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($goal['g_end_date'],"long", 0)) . "")) . "</span>			
</td>
<td class='col_c_stats altrow stats'>

<ul>
<li>" . (($goal['g_private']) ? ("--") : ("{$this->lang->words['goal']} {$goal['c_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $goal['g_amount'], 2 ) . "")) . "</li>
<li>" . (($goal['g_private']) ? ("--") : ("{$this->lang->words['received']} {$goal['c_symbol']}" . $this->registry->getClass('class_localization')->formatNumber( $goal['g_received'], 2 ) . "")) . "</li>				
</ul>

</td>
<td class='col_c_stats stats'>

<ul>
<li>" . intval($goal['donations']) . " {$this->lang->words['donations']}</li>
<li>" . intval($goal['views']) . " {$this->lang->words['views']}</li>				
</ul>

</td>	
			
</tr>
</table>
</div>
</div>
</div>
<br class='clear' />

" . ((is_array($donations) AND count($donations)) ? ("

<div class='category_block block_wrap'>
<h3 class='maintitle'>{$goal['g_name']} {$this->lang->words['donations']}</h3>
<div class='ipsBox table_wrap'>
<div class='ipsBox_container'>
<table class='ipb_table' summary=\"{$goal['g_name']} {$this->lang->words['donations']}\">
<tr class='header hide'>
<th scope='col'>{$this->lang->words['donor_name']}</th>
<th scope='col'>{$this->lang->words['donation_note']}</th>
<th scope='col' class='short'>{$this->lang->words['amount']}</th>
</tr>".$this->__f__5a3475554a873f9f65bcb843170537e2($goal,$donations,$pages)."</tr>
</table>
</div>
</div>
</div>{$pages}<br class='clear' />

") : ("
<div class='message error'>{$this->lang->words['no_active_donations']}</div>
")) . "

<br class='clear' />" . IPSLib::shareLinks( $goal['g_name'], array( 'cssClass' => 'topic_share left' )  ) . "<br class='clear' />";
return $IPBHTML;
}


function __f__5a3475554a873f9f65bcb843170537e2($goal=array(), $donations=array(), $pages='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $donations as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
<tr>
<td class='col_c_post'>
     " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userSmallPhoto' ) ? $this->registry->getClass('output')->getTemplate('global')->userSmallPhoto($r['member']) : '' ) . " 

     <ul class=\"last_post ipsType_small\">
          <li class='desc'>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donorName' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donorName($r) : '' ) . "</li>
          <li class='desc lighter'>" . IPSText::htmlspecialchars($this->registry->getClass('class_localization')->getDate($r['date'],"long", 0)) . "</li>
     </ul>
</td>
<td class='altrow'>" . (($r['note']) ? ("{$r['note']}") : ("<i>{$this->lang->words['no_note']}</i>")) . "</td>
<td class='altrow short'><strong>" . ( method_exists( $this->registry->getClass('output')->getTemplate('donate_external'), 'donationAmount' ) ? $this->registry->getClass('output')->getTemplate('donate_external')->donationAmount($r) : '' ) . "</strong></td>			
</tr>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>