<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 17 May 2016 20:43:05 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'autor' => "Author",
'autoreply_authorid' => "Auto Reply Author",
'autoreply_authorid_desc' => "This will be the post author of the automatic reply",
'autoreply_closetopic' => "Lock (close) the topic after Auto Reply is posted?",
'autoreply_on' => "Enable Auto Reply on this forum?",
'autoreply_postcontent' => "Auto Reply Content",
'autoreply_postcontent_desc' => "This will be the post content of the automatic reply",
'desc' => "To enabled auto replies to topics, go to <b>Forums</b> tab and edit the forum you want then go to <b>Auto Reply</b> tab.",
'fill_fields' => "You enabled Auto Reply on this forum, so you need to inform who will be topic author and the post content",
'forums_desc' => "Auto Reply Settings",
'mod' => "About",
'site' => "Site",
'title' => "Auto Reply",
'versao' => "Version",
'visao_geral' => "Overview",
 ); 
