<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'anonymous' => "Anonymous",
'complete' => "complete",
'donate' => "Donate",
'donation_statistics' => "Donation Statistics",
'donator' => "Donator",
'featured_donation_goals' => "Featured Donation Goals",
'fee' => "Fee",
'goal_reached' => "goal reached.",
'goal_total_met' => "Thank you for meeting our total goals, donations have been closed.",
'latest_donations' => "Latest Donations",
'member_donations' => "Member Donations",
'no_note' => "No donation note left by user. ",
'offline_donation' => "Offline Donation",
'of_this' => "of this",
'profile_no_donations' => "No member donations to display. ",
'profile_tab' => "Donations",
'still_needed' => "Still Needed",
'top_donors' => "Top Donors",
'total_donation_amount' => "Total Donation Amount",
'total_fees' => "Total Fees",
'total_goal_amount' => "Total Goal Amount",
'where_donation_tracker' => "Viewing Donation Tracker",
 ); 
