<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Mon, 16 May 2016 10:01:18 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'notify_new_feedback' => "<#NAME#>,

<#OWNER#> has just left you new feedback.

======================================================================
You can turn off this notification by visiting <#URL#>
",
'notify__notify_new_feedback' => "Notify me when someone leaves me feedback",
'subject__notify_new_feedback' => "<a href='%s'>%s</a> left you new <a href='%s'>feedback</a>",
 ); 
