<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'important' => "Set as important",
'important_set_no' => "Topic has been set to as no important",
'important_set_yes' => "Topic has been set to as important",
'important_topics' => "Important Topics",
'lock' => "Lock",
'no_important' => "Set as no important",
'open' => "Open",
'pinned' => "Pinned",
'read_more' => "Read More",
'replies' => "Replies",
'views' => "Views",
 ); 
