<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__manage_icons' => "Manage Icons",
'menu__manage_settings' => "Manage Settings",
'tools' => "Tools",
 ); 
