<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'active' => "Active",
'add_gateway' => "Install Payment Gateways",
'available_gateways' => "Available Payment Gateways",
'cant_locate_api' => "Could not locate the API in: %s",
'current' => "Current",
'debug_settings' => "Debug Settings",
'edit_gateway' => "Edit Payment Gateway",
'edit_settings' => "Edit Settings",
'enable_debug' => "Enable Debug Mode",
'enable_debug_desc' => "Debug mode will write files into your /cache folder during payment postback operations.",
'enable_sandbox' => "Enable SandBox Mode",
'enable_sandbox_desc' => "This will put your gateway into \"Test\" mode. WARNING: Do not use on a production site",
'gateway_activate' => "Activate this Gateway?",
'gateway_activate_desc' => "This will allow your members to use this option.",
'gateway_autocompletes' => "Gateway auto-completes order via return validation?",
'gateway_autocompletes_desc' => "If the gateway does not support a return validation method, then make sure this is off.",
'gateway_def_currency' => "Gateway default currency?",
'gateway_def_currency_desc' => "Select the currency this gateway uses",
'gateway_edited' => "Payment gateway '%s' edited",
'gateway_email_key' => "Gateway Associated Email Address OR associated transaction key",
'gateway_general_settings' => "General Gateway Settings",
'gateway_information' => "Gateway Information",
'gateway_installed' => "Gateway installed",
'gateway_is_installed' => "Gateway already installed",
'gateway_not_needed' => "This is not needed for all gateways.",
'gateway_public_description' => "Gateway Public Description",
'gateway_public_name' => "Gateway Public Name",
'gateway_settings' => "Gateway Settings",
'gateway_store_id' => "Gateway Store / Seller ID",
'gateway_title_required' => "You must enter a valid title for this payment gateway.",
'gateway_toggled' => "Payment gateway '%s' toggled",
'install' => "Install",
'installed' => "Installed",
'install_gateways' => "Install Gateways",
'manage_gateways' => "Manage Payment Gateways",
'member_invalid_payments' => "Member To Send \"Invalid Payment\" Emails",
'member_invalid_payments_desc' => "The board will send the specified member (display name) an email when the gateway returns an error.",
'not_locate_gateway' => "Could locate a payment gateway with the id of %s",
'no_gateways' => "There are no payment gateways installed",
'no_gateway_specified' => "No gateway specified",
'no_id_passed' => "No ID was passed - please go back and try again ",
'payment_gateway' => "Payment Gateway",
'sandbox_mode' => "SANDBOX MODE",
'transactions' => "Transactions",
 ); 
