<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'add_currency' => "Add New Currency",
'available_currencies' => "Available Currencies",
'cant_delete' => "<em>Can't Delete</em>",
'cant_delete_currency' => "Couldn't find a currency to delete.",
'code' => "Code",
'conversion_rate' => "Conversion Rate",
'currencies_updated' => "Currency settings updated",
'currency_code_exists' => "You cannot use currency code '%s' as it already exists.",
'currency_deleted' => "Currency '%s' Deleted",
'delete' => "Delete",
'description' => "Description",
'is_default' => "Default?",
'manage_currencies' => "Manage Currencies",
'save_settings' => "Save Settings",
 ); 
