<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'tb_pcr_day' => "day",
'tb_pcr_days' => "days",
'tb_pcr_month' => "month",
'tb_pcr_months' => "months",
'tb_pcr_same_pass' => "The administrator has setup that you cannot re-enter the same password when you change it",
 ); 
