<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'g_tb_pcr_days' => "Day(s)",
'g_tb_pcr_enable' => "Enable mod for this group?",
'g_tb_pcr_enable_desc' => "If set to 'No' all options below are useless.",
'g_tb_pcr_force' => "Force members in the group to change password?",
'g_tb_pcr_months' => "Month(s)",
'g_tb_pcr_time' => "After which time they have to change password?",
'g_tb_pcr_time_desc' => "1 Month = 30 days (always)",
 ); 
