<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'module__tb_pcr_manage' => "Manage Settings",
'module__tb_pcr_tools' => "Tools",
'tb_pcr_manage_settings' => "Manage Settings",
'tb_pcr_tools' => "Tools",
 ); 
