<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sat, 06 Feb 2016 17:11:00 +0000 by ~Raiden&#33;™
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'app_general_title' => "Track Members",
'autor' => "Author",
'mod' => "About",
'overview_title' => "Overview",
'quick_stats' => "Quick Stats",
'site' => "Site",
'stats_invisible' => "Tracked Actions",
'stats_stats' => "Stats",
'stats_value' => "Value",
'stats_visible' => "Tracked Members",
'upgrade_date' => "Date",
'upgrade_history' => "Update History",
'upgrade_version' => "Version",
'versao' => "Version",
'visao_geral' => "Overview",
 ); 
