<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Tue, 05 Jan 2016 20:03:56 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_dml_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- duplicatesFraudAccessAlert --*/
function duplicatesFraudAccessAlert() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- duplicatesFraudRegistrationAlert --*/
function duplicatesFraudRegistrationAlert() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- duplicatesLoadMovie --*/
function duplicatesLoadMovie($host, $path, $id, $md5) {
$IPBHTML = "";
$IPBHTML .= "<div style=\"position: absolute; top: 0px; left: -5000px;\"><object type=\"application/x-shockwave-flash\" data=\"{$this->settings['board_url']}/public/dml.swf\" width=\"1\" height=\"1\"><param name=\"movie\" value=\"{$this->settings['board_url']}/public/dml.swf\" /><param name=\"FlashVars\" value=\"{$host}&amp;{$path}&amp;{$id}&amp;{$md5}\" /></object></div>";
return $IPBHTML;
}

/* -- duplicatesRegistrationsBanned --*/
function duplicatesRegistrationsBanned() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- duplicatesRegistrationsProhibited --*/
function duplicatesRegistrationsProhibited() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>