<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Tue, 05 Jan 2016 20:03:59 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_subscriptions_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- copyright --*/
function copyright($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- currencySelectField --*/
function currencySelectField($options) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- do_generic_payscreen_with_button --*/
function do_generic_payscreen_with_button($data=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- do_manual_normal_screen --*/
function do_manual_normal_screen($new_sub_id="",$desc_string="",$ccode="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- do_manual_upgrade_screen --*/
function do_manual_upgrade_screen($new_sub_id="",$cur_id="",$desc_string="",$ccode="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- hookBadge --*/
function hookBadge($data) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- hookUserDropDownLink --*/
function hookUserDropDownLink() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- indexScreen --*/
function indexScreen($deadRows, $currRows, $upgradeRows, $newRows, $cur_id, $currency, $currencyOptions, $currencyUrl, $hasRecurringPayments=false, $canRenew=false) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- paymentMethods --*/
function paymentMethods($sub_chosen, $upgrade, $curid, $currency, $rows) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- regComplete --*/
function regComplete($currency, $packages) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- regForm --*/
function regForm($currency, $packages) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- show_ticket --*/
function show_ticket($sub="",$id="",$paid="",$extra="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- sub_msg_force --*/
function sub_msg_force() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- sub_msg_fromreg --*/
function sub_msg_fromreg() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- sub_msg_general --*/
function sub_msg_general() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- testPaymentScreen --*/
function testPaymentScreen($accept) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>