<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 1               */
/* CACHE FILE: Generated: Tue, 05 Jan 2016 20:03:54 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_topictemplate_1 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['topicTemplatePostScreen'] = array('hasOneTemplate');


}

/* -- fieldTemplate --*/
function fieldTemplate($field) {
$IPBHTML = "";
$IPBHTML .= "" . (($field['instructions']) ? ("
  <div class='ipsPad'>
    <div class='message'>{{$field['field_id']}_instr}</div>
  </div>
") : ("")) . "
      <label for='template_field_{$field['field_id']}' class='ipsField_title' data-tooltip='test'>{{$field['field_id']}_label}" . (($field['required']==1) ? ("<span class='ipsForm_required'> * </span>") : ("")) . "</label>
      <div id='ttf_{$field['field_id']}' class='ipsField_content'>    
        {{$field['field_id']}_field}" . (($field['description']) ? ("
        <br/>
        <span class='desc lighter'>{{$field['field_id']}_desc}</span>
        ") : ("")) . "
      </div>";
return $IPBHTML;
}

/* -- formatCheckbox --*/
function formatCheckbox($field) {
$IPBHTML = "";
$IPBHTML .= "<input type='checkbox' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' value='1' class='__ttf' " . (($field['value']==1) ? ("checked='checked'") : ("")) . "/>";
return $IPBHTML;
}

/* -- formatDropdown --*/
function formatDropdown($field, $options) {
$IPBHTML = "";
$IPBHTML .= "<select name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' class='__ttf'>
  <option value=''>--</option>
  ".$this->__f__a3d0b378c62b3733a8b0449b51b89665($field,$options)."</select>";
return $IPBHTML;
}


function __f__a3d0b378c62b3733a8b0449b51b89665($field, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $opt )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <option value='{$opt['value']}' " . (($opt['value']==$field['value']) ? ("SELECTED") : ("")) . ">{$opt['label']}</option>
  
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- formatMulti --*/
function formatMulti($field, $options) {
$IPBHTML = "";
$IPBHTML .= "<select name='template_field_{$field['field_id']}[]' id='template_field_{$field['field_id']}[]' multiple size='5' class='__ttf'>
  <option value=''>--</option>
  ".$this->__f__8f48a17b0949b4f333fe8cb7803a61d0($field,$options)."</select>";
return $IPBHTML;
}


function __f__8f48a17b0949b4f333fe8cb7803a61d0($field, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $opt )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <option value='{$opt['value']}' " . ((in_array($opt['value'],explode(",",$field['value']))) ? ("SELECTED") : ("")) . ">{$opt['label']}</option>
  
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- formatMultiCheckbox --*/
function formatMultiCheckbox($field, $options) {
$IPBHTML = "";
$IPBHTML .= "".$this->__f__93cf0171bc370db62295bd3c8e1dc898($field,$options)."";
return $IPBHTML;
}


function __f__93cf0171bc370db62295bd3c8e1dc898($field, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $opt )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
  <input type='checkbox' name='template_field_{$field['field_id']}[]' id='template_field_{$field['field_id']}[]' value='{$opt['value']}' class='__ttf' " . ((in_array($opt['value'],explode(",",$field['value']))) ? ("CHECKED") : ("")) . ">&nbsp;{$opt['label']}</input><br/>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- formatRadio --*/
function formatRadio($field, $options) {
$IPBHTML = "";
$IPBHTML .= "".$this->__f__aa425221f3f890bea10559135b44ac77($field,$options)."";
return $IPBHTML;
}


function __f__aa425221f3f890bea10559135b44ac77($field, $options)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $options as $opt )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
  <input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' value='{$opt['value']}' class='__ttf' " . (($opt['value']==$field['value']) ? ("CHECKED") : ("")) . ">{$opt['label']}</input>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- formatRatingField --*/
function formatRatingField($field) {
$IPBHTML = "";
$IPBHTML .= "<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_1' class='__ttf' value='1' " . (($field['value']==1) ? ("CHECKED") : ("")) . "> 1</input>&nbsp;&nbsp;
<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_2' class='__ttf' value='2' " . (($field['value']==2) ? ("CHECKED") : ("")) . "> 2</input>&nbsp;&nbsp;
<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_3' class='__ttf' value='3' " . (($field['value']==3) ? ("CHECKED") : ("")) . "> 3</input>&nbsp;&nbsp;
<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_4' class='__ttf' value='4' " . (($field['value']==4) ? ("CHECKED") : ("")) . "> 4</input>&nbsp;&nbsp;
<input type='radio' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}_5' class='__ttf' value='5' " . (($field['value']==5) ? ("CHECKED") : ("")) . "> 5</input>";
return $IPBHTML;
}

/* -- formatTextArea --*/
function formatTextArea($field) {
$IPBHTML = "";
$IPBHTML .= "<textarea name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' class='__ttf'>{$field['value']}</textarea>";
return $IPBHTML;
}

/* -- formatTextField --*/
function formatTextField($field) {
$IPBHTML = "";
$IPBHTML .= "<input type='text' name='template_field_{$field['field_id']}' id='template_field_{$field['field_id']}' value='{$field['value']}' class='__ttf'/>";
return $IPBHTML;
}

/* -- topicTemplatePostScreen --*/
function topicTemplatePostScreen($forumId, $topicId=0, $template, $currentSet, $sets) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_topictemplate', $this->_funcHooks['topicTemplatePostScreen'] ) )
{
$count_75497b473861d03683801254e62e8ca6 = is_array($this->functionData['topicTemplatePostScreen']) ? count($this->functionData['topicTemplatePostScreen']) : 0;
$this->functionData['topicTemplatePostScreen'][$count_75497b473861d03683801254e62e8ca6]['forumId'] = $forumId;
$this->functionData['topicTemplatePostScreen'][$count_75497b473861d03683801254e62e8ca6]['topicId'] = $topicId;
$this->functionData['topicTemplatePostScreen'][$count_75497b473861d03683801254e62e8ca6]['template'] = $template;
$this->functionData['topicTemplatePostScreen'][$count_75497b473861d03683801254e62e8ca6]['currentSet'] = $currentSet;
$this->functionData['topicTemplatePostScreen'][$count_75497b473861d03683801254e62e8ca6]['sets'] = $sets;
}
$IPBHTML .= "<script type='text/javascript'>
ipb.topicTemplate.forumId = {$forumId};
ipb.topicTemplate.topicId = {$topicId};
</script>
" . (($sets['required'] && count($sets['sets'])==1) ? ("<br /><br />
  <input type='hidden' name='set_id' id='set_id' value='{$currentSet['set_id']}' />
  <div id='set_description' class='ipsPad " . (($currentSet['description']) ? ("message") : ("")) . "'>{$currentSet['description']}</div>
  <br />") : ("<li class='ipsField ipsField_select'>
    <label for='set_id' class='ipsField_title'>Select Template</label>
    <div class='ipsField_content'>
      <select name='set_id' id='set_id'>
        " . ((!$sets['required']) ? ("<option value='0'>No Template</option>") : ("")) . "".$this->__f__98621abb3bc413f566d3c8e6da07ec09($forumId,$topicId,$template,$currentSet,$sets)."      </select>
      <br />
      <br />
      <div id='set_description' class='ipsPad " . (($currentSet['description']) ? ("message") : ("")) . "'>{$currentSet['description']}</div>
    </div>
  </li>")) . "
<div id='set_fields'>
{$template}
</div>";
return $IPBHTML;
}


function __f__98621abb3bc413f566d3c8e6da07ec09($forumId, $topicId=0, $template, $currentSet, $sets)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sets['sets'] as $set )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
          <option value='{$set['set_id']}' " . (($set['set_id']==$currentSet['set_id']) ? ("SELECTED") : ("")) . ">{$set['name']}</option>
        
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicTemplatePostTemplate --*/
function topicTemplatePostTemplate($fields) {
$IPBHTML = "";
$IPBHTML .= "" . ((is_array($fields) && count($fields)) ? ("".$this->__f__f97e8c1de0c9442ad637042489485020($fields)."") : ("")) . "";
return $IPBHTML;
}


function __f__f97e8c1de0c9442ad637042489485020($fields)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $fields as $field )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
    <li class='ipsField'>
      {$field}
    </li>
  
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>